grab_car_data:
  fields:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: ev_guest
calculate:
  fields:
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: ev_guest
