grab_car_data:
  fields:
    entry_id:
      required: true
      example: "1234abcd"
      selector:
        text:
calculate:
  fields:
    entry_id:
      required: true
      example: "1234abcd"
      selector:
        text:
